name: my_new_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.0.5
  get_it: ^9.2.1

  # Annotations for code generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: 4.1.0

  # Networking & Utilities
  dio: ^5.11.0
  pretty_dio_logger: ^1.4.0
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  easy_localization: ^3.0.8
  flutter_native_splash: ^2.4.8
  flutter_svg: ^2.3.0
  firebase_core: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generators
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: 8.1.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/