default_platform(:android)

platform :android do

  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    # 3. رفع الـ APK لمستخدمي Firebase App Distribution
    firebase_app_distribution(
      app: "1:825707952555:android:d6c62e607283af7d3fbaee",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "hamzabdo167@gmail.com",
      release_notes: "First Fastlane Firebase Distribution YouTube Video!"
    )
  end

end